name: pipeline-azure-resource-provision

on:
    workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    plan-apply:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Azure login setup
              uses: azure/login@v2
              with:
                creds: ${{ secrets.AZIRE_CREDENTIALS }}               

            - name: terraform setup
              uses: hashicorp/setup-terraform@v3
              
            - name: Terraform Formate Codes
              run:  terraform fmt

            - name: Terraform Validate Codes
              run: terraform validate

            - name: Terraform Plan
              run: terraform plan -out=tfplan

            - name: Terraform Apply
              if: github.ref == 'refs/heads/main'
              run: terraform plan -auto-approve tfplan